# Generated by Django 5.2.5 on 2025-08-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emplayee',
            new_name='Employee',
        ),
    ]
